baseURL = "http://realvz.github.io/UpdateThinSoftware/"
languageCode = "en-us"
publishDir = "docs"
title = "My New Hugo Site"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
